algoritmo "IDADE"
var
   ano, nasc, idade: inteiro
inicio
      Escreva ("qual ano atual?")
      leia(ano)
      escreva("qual ano de nascimento? ")
      leia(nasc)
      idade <- ano - nasc)
      escreva("sua idade é de", idade)
      
      se (idade >= 18) entao
         escreva(" você pode digirir ")
      senao
         escreva(" voce pode não dirigir ")
      fimse
fimalgoritmo